CREATE TABLE IF NOT EXISTS `ai_memo_list` (
    `id` VARCHAR(32) NOT NULL COMMENT '服务端主键',
    `user_id` BIGINT NOT NULL COMMENT '所属用户ID',
    `memo_id` VARCHAR(64) NOT NULL COMMENT '客户端清单ID',
    `name` VARCHAR(100) NOT NULL COMMENT '清单名称',
    `color` VARCHAR(32) DEFAULT '#F8B800' COMMENT '清单颜色',
    `client_created_at` BIGINT DEFAULT 0 COMMENT '客户端创建时间毫秒',
    `client_updated_at` BIGINT DEFAULT 0 COMMENT '客户端更新时间毫秒',
    `deleted_at` BIGINT DEFAULT 0 COMMENT '客户端删除时间毫秒',
    `sort_order` BIGINT DEFAULT 0 COMMENT '客户端排序值',
    `creator` BIGINT COMMENT '创建者',
    `create_date` DATETIME COMMENT '创建时间',
    `updater` BIGINT COMMENT '更新者',
    `update_date` DATETIME COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_memo_list_user_memo` (`user_id`, `memo_id`),
    KEY `idx_ai_memo_list_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='便单清单';

CREATE TABLE IF NOT EXISTS `ai_memo_tag` (
    `id` VARCHAR(32) NOT NULL COMMENT '服务端主键',
    `user_id` BIGINT NOT NULL COMMENT '所属用户ID',
    `memo_id` VARCHAR(64) NOT NULL COMMENT '客户端标签ID',
    `name` VARCHAR(100) NOT NULL COMMENT '标签名称',
    `color` VARCHAR(32) DEFAULT '#F8B800' COMMENT '标签颜色',
    `client_created_at` BIGINT DEFAULT 0 COMMENT '客户端创建时间毫秒',
    `client_updated_at` BIGINT DEFAULT 0 COMMENT '客户端更新时间毫秒',
    `deleted_at` BIGINT DEFAULT 0 COMMENT '客户端删除时间毫秒',
    `creator` BIGINT COMMENT '创建者',
    `create_date` DATETIME COMMENT '创建时间',
    `updater` BIGINT COMMENT '更新者',
    `update_date` DATETIME COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_memo_tag_user_memo` (`user_id`, `memo_id`),
    KEY `idx_ai_memo_tag_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='便单标签';

CREATE TABLE IF NOT EXISTS `ai_memo_item` (
    `id` VARCHAR(32) NOT NULL COMMENT '服务端主键',
    `user_id` BIGINT NOT NULL COMMENT '所属用户ID',
    `memo_id` VARCHAR(64) NOT NULL COMMENT '客户端条目ID',
    `type` VARCHAR(16) DEFAULT 'memo' COMMENT 'memo/todo',
    `title` VARCHAR(255) NOT NULL COMMENT '标题',
    `content` TEXT COMMENT '内容',
    `list_id` VARCHAR(64) DEFAULT 'inbox' COMMENT '客户端清单ID',
    `list_name` VARCHAR(100) DEFAULT '默认清单' COMMENT '清单名称快照',
    `status` VARCHAR(16) DEFAULT 'open' COMMENT 'open/done',
    `priority` VARCHAR(16) DEFAULT 'normal' COMMENT 'low/normal/high/urgent',
    `tags_json` JSON COMMENT '标签名称数组',
    `subtasks_json` JSON COMMENT '子任务数组',
    `reminders_json` JSON COMMENT '提醒数组',
    `attachments_json` JSON COMMENT '附件元数据数组',
    `start_at` VARCHAR(64) DEFAULT '' COMMENT '开始时间字符串',
    `due_at` VARCHAR(64) DEFAULT '' COMMENT '截止时间字符串',
    `all_day` TINYINT(1) DEFAULT 0 COMMENT '是否全天',
    `repeat_rule` VARCHAR(255) DEFAULT '' COMMENT '重复规则',
    `color` VARCHAR(32) DEFAULT '' COMMENT '条目颜色',
    `client_created_at` BIGINT DEFAULT 0 COMMENT '客户端创建时间毫秒',
    `client_updated_at` BIGINT DEFAULT 0 COMMENT '客户端更新时间毫秒',
    `deleted_at` BIGINT DEFAULT 0 COMMENT '客户端删除时间毫秒',
    `archived_at` BIGINT DEFAULT 0 COMMENT '客户端归档时间毫秒',
    `sort_order` BIGINT DEFAULT 0 COMMENT '客户端排序值',
    `version` INT DEFAULT 1 COMMENT '服务端版本',
    `creator` BIGINT COMMENT '创建者',
    `create_date` DATETIME COMMENT '创建时间',
    `updater` BIGINT COMMENT '更新者',
    `update_date` DATETIME COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_memo_item_user_memo` (`user_id`, `memo_id`),
    KEY `idx_ai_memo_item_user_updated` (`user_id`, `client_updated_at`),
    KEY `idx_ai_memo_item_user_status` (`user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='便单条目';
